version: '3'
services:
  css_container:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: css_container
    volumes:
      - ${CSS_DIR}:/css # path to counter-strike source directory
      - ${SCREENSHOT_DIR}:/screenshots
    restart: unless-stopped
